import tkinter as tk

def colours():
    s=a.get()
    if s==1:
        root.config(bg="Red")
        b.config(bg="Red")
        b1.config(bg="Red")
        b2.config(bg="Red")
        b3.config(bg="Red")
        b4.config(bg="Red")
        b5.config(bg="Red")
        b6.config(bg="Red")
    elif s==2:
        root.config(bg="Yellow")
        b.config(bg="Yellow")
        b1.config(bg="Yellow")
        b2.config(bg="Yellow")
        b3.config(bg="Yellow")
        b4.config(bg="Yellow")
        b5.config(bg="Yellow")
        b6.config(bg="Yellow")
    elif s==3:
        root.config(bg="Black")
        b.config(bg="Black")
        b1.config(bg="Black")
        b2.config(bg="Black")
        b3.config(bg="Black")
        b4.config(bg="Black")
        b5.config(bg="Black")
        b6.config(bg="Black")
    elif s==4:
        root.config(bg="Purple")
        b.config(bg="Purple")
        b1.config(bg="Purple")
        b2.config(bg="Purple")
        b3.config(bg="Purple")
        b4.config(bg="Purple")
        b5.config(bg="Purple")
        b6.config(bg="Purple")
    elif s==5:
        root.config(bg="Green")
        b.config(bg="Green")
        b1.config(bg="Green")
        b2.config(bg="Green")
        b3.config(bg="Green")
        b4.config(bg="Green")
        b5.config(bg="Green")
        b6.config(bg="Green")
    elif s==7:
        root.config(bg="Gold")
        b.config(bg="Gold")
        b1.config(bg="Gold")
        b2.config(bg="Gold")
        b3.config(bg="Gold")
        b4.config(bg="Gold")
        b5.config(bg="Gold")
        b6.config(bg="Gold")
    elif s==6:
        root.config(bg="Blue")
        b.config(bg="Blue")
        b1.config(bg="Blue")
        b2.config(bg="Blue")
        b3.config(bg="Blue")
        b4.config(bg="Blue")
        b5.config(bg="Blue")
        b6.config(bg="Blue")

root=tk.Tk()
root.title("Triangle")
root.geometry("700x700")

a=tk.IntVar()
b=tk.Radiobutton(root,text='Red',variable=a,value=1,command=colours)
b1=tk.Radiobutton(root,text='Yellow',variable=a,value=2,command=colours)
b2=tk.Radiobutton(root,text='Black',variable=a,value=3,command=colours)
b3=tk.Radiobutton(root,text='Purple',variable=a,value=4,command=colours)
b4=tk.Radiobutton(root,text='Green',variable=a,value=5,command=colours)
b5=tk.Radiobutton(root,text='Gold',variable=a,value=6,command=colours)
b6=tk.Radiobutton(root,text='Blue',variable=a,value=7,command=colours)
b.grid()
b1.grid()
b2.grid()
b3.grid()
b4.grid()
b5.grid()
b6.grid()
tk.mainloop()